/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingNewsAndMediaRouteImport } from './routes/_landing/news-and-media'
import { Route as LandingDigitalServicesRouteImport } from './routes/_landing/digital-services'
import { Route as LandingCadServicesRouteImport } from './routes/_landing/cad-services'
import { Route as LandingAboutUsRouteImport } from './routes/_landing/about-us'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as LandingNewsAndMediaIndexRouteImport } from './routes/_landing/news-and-media.index'
import { Route as LandingDigitalServicesIndexRouteImport } from './routes/_landing/digital-services.index'
import { Route as LandingCadServicesIndexRouteImport } from './routes/_landing/cad-services.index'
import { Route as LandingNewsAndMediaAllPostsRouteImport } from './routes/_landing/news-and-media_.all-posts'
import { Route as LandingNewsAndMediaSlugRouteImport } from './routes/_landing/news-and-media.$slug'
import { Route as LandingDigitalServicesSlugRouteImport } from './routes/_landing/digital-services.$slug'
import { Route as LandingCadServicesSlugRouteImport } from './routes/_landing/cad-services.$slug'
import { Route as LandingAboutUsVisionRouteImport } from './routes/_landing/about-us_.vision'
import { Route as LandingAboutUsOverviewRouteImport } from './routes/_landing/about-us_.overview'
import { Route as AdminAdminMgmtServicesRouteImport } from './routes/_admin/admin.mgmt.services'
import { Route as AdminAdminMgmtServicesTypesRouteImport } from './routes/_admin/admin.mgmt.services.types'
import { Route as AdminAdminMgmtServicesCreateRouteImport } from './routes/_admin/admin.mgmt.services.create'
import { Route as AdminAdminMgmtPostsNewRouteImport } from './routes/_admin/admin.mgmt.posts.new'
import { Route as AdminAdminMgmtPostsIdEditRouteImport } from './routes/_admin/admin.mgmt.posts.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingNewsAndMediaRoute = LandingNewsAndMediaRouteImport.update({
  id: '/news-and-media',
  path: '/news-and-media',
  getParentRoute: () => LandingRoute,
} as any)
const LandingDigitalServicesRoute = LandingDigitalServicesRouteImport.update({
  id: '/digital-services',
  path: '/digital-services',
  getParentRoute: () => LandingRoute,
} as any)
const LandingCadServicesRoute = LandingCadServicesRouteImport.update({
  id: '/cad-services',
  path: '/cad-services',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutUsRoute = LandingAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => LandingRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const LandingNewsAndMediaIndexRoute =
  LandingNewsAndMediaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LandingNewsAndMediaRoute,
  } as any)
const LandingDigitalServicesIndexRoute =
  LandingDigitalServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LandingDigitalServicesRoute,
  } as any)
const LandingCadServicesIndexRoute = LandingCadServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingCadServicesRoute,
} as any)
const LandingNewsAndMediaAllPostsRoute =
  LandingNewsAndMediaAllPostsRouteImport.update({
    id: '/news-and-media_/all-posts',
    path: '/news-and-media/all-posts',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingNewsAndMediaSlugRoute = LandingNewsAndMediaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LandingNewsAndMediaRoute,
} as any)
const LandingDigitalServicesSlugRoute =
  LandingDigitalServicesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => LandingDigitalServicesRoute,
  } as any)
const LandingCadServicesSlugRoute = LandingCadServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LandingCadServicesRoute,
} as any)
const LandingAboutUsVisionRoute = LandingAboutUsVisionRouteImport.update({
  id: '/about-us_/vision',
  path: '/about-us/vision',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutUsOverviewRoute = LandingAboutUsOverviewRouteImport.update({
  id: '/about-us_/overview',
  path: '/about-us/overview',
  getParentRoute: () => LandingRoute,
} as any)
const AdminAdminMgmtServicesRoute = AdminAdminMgmtServicesRouteImport.update({
  id: '/mgmt/services',
  path: '/mgmt/services',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMgmtServicesTypesRoute =
  AdminAdminMgmtServicesTypesRouteImport.update({
    id: '/types',
    path: '/types',
    getParentRoute: () => AdminAdminMgmtServicesRoute,
  } as any)
const AdminAdminMgmtServicesCreateRoute =
  AdminAdminMgmtServicesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AdminAdminMgmtServicesRoute,
  } as any)
const AdminAdminMgmtPostsNewRoute = AdminAdminMgmtPostsNewRouteImport.update({
  id: '/mgmt/posts/new',
  path: '/mgmt/posts/new',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMgmtPostsIdEditRoute =
  AdminAdminMgmtPostsIdEditRouteImport.update({
    id: '/mgmt/posts/$id/edit',
    path: '/mgmt/posts/$id/edit',
    getParentRoute: () => AdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof LandingIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/about-us': typeof LandingAboutUsRoute
  '/cad-services': typeof LandingCadServicesRouteWithChildren
  '/digital-services': typeof LandingDigitalServicesRouteWithChildren
  '/news-and-media': typeof LandingNewsAndMediaRouteWithChildren
  '/about-us/overview': typeof LandingAboutUsOverviewRoute
  '/about-us/vision': typeof LandingAboutUsVisionRoute
  '/cad-services/$slug': typeof LandingCadServicesSlugRoute
  '/digital-services/$slug': typeof LandingDigitalServicesSlugRoute
  '/news-and-media/$slug': typeof LandingNewsAndMediaSlugRoute
  '/news-and-media/all-posts': typeof LandingNewsAndMediaAllPostsRoute
  '/cad-services/': typeof LandingCadServicesIndexRoute
  '/digital-services/': typeof LandingDigitalServicesIndexRoute
  '/news-and-media/': typeof LandingNewsAndMediaIndexRoute
  '/admin/mgmt/services': typeof AdminAdminMgmtServicesRouteWithChildren
  '/admin/mgmt/posts/new': typeof AdminAdminMgmtPostsNewRoute
  '/admin/mgmt/services/create': typeof AdminAdminMgmtServicesCreateRoute
  '/admin/mgmt/services/types': typeof AdminAdminMgmtServicesTypesRoute
  '/admin/mgmt/posts/$id/edit': typeof AdminAdminMgmtPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof LandingIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/about-us': typeof LandingAboutUsRoute
  '/about-us/overview': typeof LandingAboutUsOverviewRoute
  '/about-us/vision': typeof LandingAboutUsVisionRoute
  '/cad-services/$slug': typeof LandingCadServicesSlugRoute
  '/digital-services/$slug': typeof LandingDigitalServicesSlugRoute
  '/news-and-media/$slug': typeof LandingNewsAndMediaSlugRoute
  '/news-and-media/all-posts': typeof LandingNewsAndMediaAllPostsRoute
  '/cad-services': typeof LandingCadServicesIndexRoute
  '/digital-services': typeof LandingDigitalServicesIndexRoute
  '/news-and-media': typeof LandingNewsAndMediaIndexRoute
  '/admin/mgmt/services': typeof AdminAdminMgmtServicesRouteWithChildren
  '/admin/mgmt/posts/new': typeof AdminAdminMgmtPostsNewRoute
  '/admin/mgmt/services/create': typeof AdminAdminMgmtServicesCreateRoute
  '/admin/mgmt/services/types': typeof AdminAdminMgmtServicesTypesRoute
  '/admin/mgmt/posts/$id/edit': typeof AdminAdminMgmtPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_landing/about-us': typeof LandingAboutUsRoute
  '/_landing/cad-services': typeof LandingCadServicesRouteWithChildren
  '/_landing/digital-services': typeof LandingDigitalServicesRouteWithChildren
  '/_landing/news-and-media': typeof LandingNewsAndMediaRouteWithChildren
  '/_landing/': typeof LandingIndexRoute
  '/_landing/about-us_/overview': typeof LandingAboutUsOverviewRoute
  '/_landing/about-us_/vision': typeof LandingAboutUsVisionRoute
  '/_landing/cad-services/$slug': typeof LandingCadServicesSlugRoute
  '/_landing/digital-services/$slug': typeof LandingDigitalServicesSlugRoute
  '/_landing/news-and-media/$slug': typeof LandingNewsAndMediaSlugRoute
  '/_landing/news-and-media_/all-posts': typeof LandingNewsAndMediaAllPostsRoute
  '/_landing/cad-services/': typeof LandingCadServicesIndexRoute
  '/_landing/digital-services/': typeof LandingDigitalServicesIndexRoute
  '/_landing/news-and-media/': typeof LandingNewsAndMediaIndexRoute
  '/_admin/admin/mgmt/services': typeof AdminAdminMgmtServicesRouteWithChildren
  '/_admin/admin/mgmt/posts/new': typeof AdminAdminMgmtPostsNewRoute
  '/_admin/admin/mgmt/services/create': typeof AdminAdminMgmtServicesCreateRoute
  '/_admin/admin/mgmt/services/types': typeof AdminAdminMgmtServicesTypesRoute
  '/_admin/admin/mgmt/posts/$id/edit': typeof AdminAdminMgmtPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/login'
    | '/admin'
    | '/about-us'
    | '/cad-services'
    | '/digital-services'
    | '/news-and-media'
    | '/about-us/overview'
    | '/about-us/vision'
    | '/cad-services/$slug'
    | '/digital-services/$slug'
    | '/news-and-media/$slug'
    | '/news-and-media/all-posts'
    | '/cad-services/'
    | '/digital-services/'
    | '/news-and-media/'
    | '/admin/mgmt/services'
    | '/admin/mgmt/posts/new'
    | '/admin/mgmt/services/create'
    | '/admin/mgmt/services/types'
    | '/admin/mgmt/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/login'
    | '/admin'
    | '/about-us'
    | '/about-us/overview'
    | '/about-us/vision'
    | '/cad-services/$slug'
    | '/digital-services/$slug'
    | '/news-and-media/$slug'
    | '/news-and-media/all-posts'
    | '/cad-services'
    | '/digital-services'
    | '/news-and-media'
    | '/admin/mgmt/services'
    | '/admin/mgmt/posts/new'
    | '/admin/mgmt/services/create'
    | '/admin/mgmt/services/types'
    | '/admin/mgmt/posts/$id/edit'
  id:
    | '__root__'
    | '/$'
    | '/_admin'
    | '/_landing'
    | '/login'
    | '/_admin/admin'
    | '/_landing/about-us'
    | '/_landing/cad-services'
    | '/_landing/digital-services'
    | '/_landing/news-and-media'
    | '/_landing/'
    | '/_landing/about-us_/overview'
    | '/_landing/about-us_/vision'
    | '/_landing/cad-services/$slug'
    | '/_landing/digital-services/$slug'
    | '/_landing/news-and-media/$slug'
    | '/_landing/news-and-media_/all-posts'
    | '/_landing/cad-services/'
    | '/_landing/digital-services/'
    | '/_landing/news-and-media/'
    | '/_admin/admin/mgmt/services'
    | '/_admin/admin/mgmt/posts/new'
    | '/_admin/admin/mgmt/services/create'
    | '/_admin/admin/mgmt/services/types'
    | '/_admin/admin/mgmt/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/news-and-media': {
      id: '/_landing/news-and-media'
      path: '/news-and-media'
      fullPath: '/news-and-media'
      preLoaderRoute: typeof LandingNewsAndMediaRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/digital-services': {
      id: '/_landing/digital-services'
      path: '/digital-services'
      fullPath: '/digital-services'
      preLoaderRoute: typeof LandingDigitalServicesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/cad-services': {
      id: '/_landing/cad-services'
      path: '/cad-services'
      fullPath: '/cad-services'
      preLoaderRoute: typeof LandingCadServicesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about-us': {
      id: '/_landing/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof LandingAboutUsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_landing/news-and-media/': {
      id: '/_landing/news-and-media/'
      path: '/'
      fullPath: '/news-and-media/'
      preLoaderRoute: typeof LandingNewsAndMediaIndexRouteImport
      parentRoute: typeof LandingNewsAndMediaRoute
    }
    '/_landing/digital-services/': {
      id: '/_landing/digital-services/'
      path: '/'
      fullPath: '/digital-services/'
      preLoaderRoute: typeof LandingDigitalServicesIndexRouteImport
      parentRoute: typeof LandingDigitalServicesRoute
    }
    '/_landing/cad-services/': {
      id: '/_landing/cad-services/'
      path: '/'
      fullPath: '/cad-services/'
      preLoaderRoute: typeof LandingCadServicesIndexRouteImport
      parentRoute: typeof LandingCadServicesRoute
    }
    '/_landing/news-and-media_/all-posts': {
      id: '/_landing/news-and-media_/all-posts'
      path: '/news-and-media/all-posts'
      fullPath: '/news-and-media/all-posts'
      preLoaderRoute: typeof LandingNewsAndMediaAllPostsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/news-and-media/$slug': {
      id: '/_landing/news-and-media/$slug'
      path: '/$slug'
      fullPath: '/news-and-media/$slug'
      preLoaderRoute: typeof LandingNewsAndMediaSlugRouteImport
      parentRoute: typeof LandingNewsAndMediaRoute
    }
    '/_landing/digital-services/$slug': {
      id: '/_landing/digital-services/$slug'
      path: '/$slug'
      fullPath: '/digital-services/$slug'
      preLoaderRoute: typeof LandingDigitalServicesSlugRouteImport
      parentRoute: typeof LandingDigitalServicesRoute
    }
    '/_landing/cad-services/$slug': {
      id: '/_landing/cad-services/$slug'
      path: '/$slug'
      fullPath: '/cad-services/$slug'
      preLoaderRoute: typeof LandingCadServicesSlugRouteImport
      parentRoute: typeof LandingCadServicesRoute
    }
    '/_landing/about-us_/vision': {
      id: '/_landing/about-us_/vision'
      path: '/about-us/vision'
      fullPath: '/about-us/vision'
      preLoaderRoute: typeof LandingAboutUsVisionRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about-us_/overview': {
      id: '/_landing/about-us_/overview'
      path: '/about-us/overview'
      fullPath: '/about-us/overview'
      preLoaderRoute: typeof LandingAboutUsOverviewRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_admin/admin/mgmt/services': {
      id: '/_admin/admin/mgmt/services'
      path: '/mgmt/services'
      fullPath: '/admin/mgmt/services'
      preLoaderRoute: typeof AdminAdminMgmtServicesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/mgmt/services/types': {
      id: '/_admin/admin/mgmt/services/types'
      path: '/types'
      fullPath: '/admin/mgmt/services/types'
      preLoaderRoute: typeof AdminAdminMgmtServicesTypesRouteImport
      parentRoute: typeof AdminAdminMgmtServicesRoute
    }
    '/_admin/admin/mgmt/services/create': {
      id: '/_admin/admin/mgmt/services/create'
      path: '/create'
      fullPath: '/admin/mgmt/services/create'
      preLoaderRoute: typeof AdminAdminMgmtServicesCreateRouteImport
      parentRoute: typeof AdminAdminMgmtServicesRoute
    }
    '/_admin/admin/mgmt/posts/new': {
      id: '/_admin/admin/mgmt/posts/new'
      path: '/mgmt/posts/new'
      fullPath: '/admin/mgmt/posts/new'
      preLoaderRoute: typeof AdminAdminMgmtPostsNewRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/mgmt/posts/$id/edit': {
      id: '/_admin/admin/mgmt/posts/$id/edit'
      path: '/mgmt/posts/$id/edit'
      fullPath: '/admin/mgmt/posts/$id/edit'
      preLoaderRoute: typeof AdminAdminMgmtPostsIdEditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminMgmtServicesRouteChildren {
  AdminAdminMgmtServicesCreateRoute: typeof AdminAdminMgmtServicesCreateRoute
  AdminAdminMgmtServicesTypesRoute: typeof AdminAdminMgmtServicesTypesRoute
}

const AdminAdminMgmtServicesRouteChildren: AdminAdminMgmtServicesRouteChildren =
  {
    AdminAdminMgmtServicesCreateRoute: AdminAdminMgmtServicesCreateRoute,
    AdminAdminMgmtServicesTypesRoute: AdminAdminMgmtServicesTypesRoute,
  }

const AdminAdminMgmtServicesRouteWithChildren =
  AdminAdminMgmtServicesRoute._addFileChildren(
    AdminAdminMgmtServicesRouteChildren,
  )

interface AdminAdminRouteChildren {
  AdminAdminMgmtServicesRoute: typeof AdminAdminMgmtServicesRouteWithChildren
  AdminAdminMgmtPostsNewRoute: typeof AdminAdminMgmtPostsNewRoute
  AdminAdminMgmtPostsIdEditRoute: typeof AdminAdminMgmtPostsIdEditRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminMgmtServicesRoute: AdminAdminMgmtServicesRouteWithChildren,
  AdminAdminMgmtPostsNewRoute: AdminAdminMgmtPostsNewRoute,
  AdminAdminMgmtPostsIdEditRoute: AdminAdminMgmtPostsIdEditRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LandingCadServicesRouteChildren {
  LandingCadServicesSlugRoute: typeof LandingCadServicesSlugRoute
  LandingCadServicesIndexRoute: typeof LandingCadServicesIndexRoute
}

const LandingCadServicesRouteChildren: LandingCadServicesRouteChildren = {
  LandingCadServicesSlugRoute: LandingCadServicesSlugRoute,
  LandingCadServicesIndexRoute: LandingCadServicesIndexRoute,
}

const LandingCadServicesRouteWithChildren =
  LandingCadServicesRoute._addFileChildren(LandingCadServicesRouteChildren)

interface LandingDigitalServicesRouteChildren {
  LandingDigitalServicesSlugRoute: typeof LandingDigitalServicesSlugRoute
  LandingDigitalServicesIndexRoute: typeof LandingDigitalServicesIndexRoute
}

const LandingDigitalServicesRouteChildren: LandingDigitalServicesRouteChildren =
  {
    LandingDigitalServicesSlugRoute: LandingDigitalServicesSlugRoute,
    LandingDigitalServicesIndexRoute: LandingDigitalServicesIndexRoute,
  }

const LandingDigitalServicesRouteWithChildren =
  LandingDigitalServicesRoute._addFileChildren(
    LandingDigitalServicesRouteChildren,
  )

interface LandingNewsAndMediaRouteChildren {
  LandingNewsAndMediaSlugRoute: typeof LandingNewsAndMediaSlugRoute
  LandingNewsAndMediaIndexRoute: typeof LandingNewsAndMediaIndexRoute
}

const LandingNewsAndMediaRouteChildren: LandingNewsAndMediaRouteChildren = {
  LandingNewsAndMediaSlugRoute: LandingNewsAndMediaSlugRoute,
  LandingNewsAndMediaIndexRoute: LandingNewsAndMediaIndexRoute,
}

const LandingNewsAndMediaRouteWithChildren =
  LandingNewsAndMediaRoute._addFileChildren(LandingNewsAndMediaRouteChildren)

interface LandingRouteChildren {
  LandingAboutUsRoute: typeof LandingAboutUsRoute
  LandingCadServicesRoute: typeof LandingCadServicesRouteWithChildren
  LandingDigitalServicesRoute: typeof LandingDigitalServicesRouteWithChildren
  LandingNewsAndMediaRoute: typeof LandingNewsAndMediaRouteWithChildren
  LandingIndexRoute: typeof LandingIndexRoute
  LandingAboutUsOverviewRoute: typeof LandingAboutUsOverviewRoute
  LandingAboutUsVisionRoute: typeof LandingAboutUsVisionRoute
  LandingNewsAndMediaAllPostsRoute: typeof LandingNewsAndMediaAllPostsRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAboutUsRoute: LandingAboutUsRoute,
  LandingCadServicesRoute: LandingCadServicesRouteWithChildren,
  LandingDigitalServicesRoute: LandingDigitalServicesRouteWithChildren,
  LandingNewsAndMediaRoute: LandingNewsAndMediaRouteWithChildren,
  LandingIndexRoute: LandingIndexRoute,
  LandingAboutUsOverviewRoute: LandingAboutUsOverviewRoute,
  LandingAboutUsVisionRoute: LandingAboutUsVisionRoute,
  LandingNewsAndMediaAllPostsRoute: LandingNewsAndMediaAllPostsRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
